# Generated by Django 4.1.4 on 2022-12-10 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=100)),
                ('privado', models.BooleanField()),
                ('categoría', models.CharField(blank=True, choices=[('tech', 'tech'), ('offtopic', 'offtopic'), ('hardware', 'hardware'), ('software', 'software')], max_length=255)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
